### ISSUE TITLE
Restarting of failed processes

### ISSUE THREAD

**Issue by benmccann** [flynn-archive/flynn-host#2]
I'm trying to go through some of the flynn code right now. I love how simple it is. I tried contributing a bit to cloud foundry but got totally turned off by how massive it was (and the fact that they wouldn't accept my patches to make it run on anything newer than ubuntu 10.04 :-)

The biggest thing that I can't find is how flynn plans to handle failed processes. I think that for most services you would want them restarted automatically. If you wanted to get smarter about it you could detect a process that's flapping trying to come up, failing, being restarted repeatedly and just let it stay down.

**Comment by titanous** [comment]
There are two options:
1. Require schedulers to handle failed jobs. (they can subscribe to an event stream from lorne and watch to see if their process dies "unexpectedly")
2. Add an option for lorne to restart the job on the same host if the process has a non-zero exit code. For sanity, this will require detection of flapping.

For now we're going to stick with option one, but I've got this bouncing around in the back of my head still and haven't decided on anything permanently.

**Comment by benmccann** [comment]
Yeah, they both make some sense, and I had thought about both as well. I think detection of flapping would be even more important for the first option. Imagine that your task keeps dying and the scheduler continuously reschedules it on different machines bouncing all around the cluster. I think the second option might become easier to manage because all the logs are on the same machine.

**Comment by titanous** [comment]
Oh yeah, both require flap detection. Pushing it to the scheduler (in Layer 1) makes Layer 0 strictly simpler, which is why we're using that option. It's also more flexible, as the definition of failure and what should be done about it is not a static thing.

**Comment by benmccann** [comment]
Yeah, makes sense. Especially if it's easy for the scheduler give preference to the last machine the service was run on to avoid the job bouncing around the cluster.

**Comment by progrium** [comment]
Our out of box scheduler is likely to work like Heroku -- restart it a
couple times and if it continues to fail, leave it failed.

On Sat, Nov 16, 2013 at 7:04 PM, Jonathan Rudenberg <
notifications@github.com> wrote:

> Reopened #2 https://github.com/flynn/lorne/issues/2.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/lorne/issues/2
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by progrium** [comment]
I think a philosophy of "pushing it to the edge" would mean that jobs can be given a flag that tells the host it should try to keep it alive as much as it can. If it's unable to because it continues to crash or because the host no longer has resources, then the scheduler can step in and decide what to do. This also helps relieve scheduling cycles related to host locality... if a job needs to run on a particular host or type of host, it's implied that the job would likely be scheduled on the same or similar host, so by assuming it should be fine to "reschedule" on the same host by restarting, you get a reasonable default behavior without a scheduler having to step in.

**Comment by titanous** [comment]
@progrium yeah, I'm fine with this as long as we have a very clear definition of "flapping".
