### ISSUE TITLE
Use upstream go-dockerclient

### ISSUE THREAD

**Issue by benmccann** [flynn-archive/flynn-host#4]
I've gotten all changes from flynn/go-dockerclient merged back upstream to [fsouza/go-dockerclient](https://github.com/fsouza/go-dockerclient).

The only change left is https://github.com/flynn/go-dockerclient/commit/99d6d1c02b3d90e7367c6ce74e79461139d70790. It adds a Name field in docker.go [which is a file that has been copied and forked dotcloud/docker's container.go](https://github.com/dotcloud/docker/blob/master/container.go). Would you guys be able to handle this last one? You'll have to either get docker to add a Name field or stop using it here in order to user the upstream go-dockerclient.

**Comment by progrium** [comment]
Wow, thanks for helping with that. I'm sure we'll figure something out for
that last one.

On Mon, Jan 6, 2014 at 3:18 PM, Ben McCann notifications@github.com wrote:

> I've gotten all changes from flynn/go-dockerclient merged back upstream to
> fsouza/go-dockerclient.
> 
> The only change left is flynn/go-dockerclient@99d6d1chttps://github.com/flynn/go-dockerclient/commit/99d6d1c02b3d90e7367c6ce74e79461139d70790.
> It adds a Name field in docker.go which is a file that has been copied
> and forked dotcloud/docker's container.gohttps://github.com/dotcloud/docker/blob/master/container.go.
> Would you guys be able to handle this last one? You'll have to either get
> docker to add a Name field or stop using it here in order to user the
> upstream go-dockerclient.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/lorne/issues/4
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by lmars** [comment]
I would like to use the upstream go-dockerclient so I can specify registry credentials (i.e. fsouza/go-dockerclient@a58121d0410805889b3843b048483c4372605346).

I see you can now specify a Name in upstream (fsouza/go-dockerclient@dfba9745e213049e98519ede60186916fbe09d92), could we now switch to that?

**Comment by titanous** [comment]
@lmars Yeah, I'm fine with that if everything got upstreamed. We just need to actually do the switchover and test. Are you interested in giving it a shot?

**Comment by lmars** [comment]
@titanous yeh I'll give it a go later

**Comment by lmars** [comment]
@titanous there were some things not merged upstream (e.g. [the Event stream](https://github.com/flynn/go-dockerclient/commit/eb0437792178bf6021b24f6a881773bb11f9c0f7)) so I did my best at rebasing on top of upstream master:

https://github.com/flynn/go-dockerclient/compare/upstream-rebase

But this has lead to a few errors: https://travis-ci.org/flynn/go-dockerclient/jobs/19887951

I'm only just getting started with Go so don't really know how to fix those.

**Comment by benmccann** [comment]
@lmars it looks like there's other work going on upstream for events, so after https://github.com/fsouza/go-dockerclient/pull/72 is merged then hopefully you'll be able to use the upstream library by switching to this new api

I think that a lot of the other commits shouldn't be merged to upstream. E.g. the ones removing unused code, configuring Travis, etc.

**Comment by fsouza** [comment]
Some removed code in the fork are worth removing in upstream (the raw terminal thing in the hijack method, for example).

Regarding the event stream support, I do prefer flynn's implementation, but we need some tests. I've asked @jhulten to use your approach, adding tests.

**Comment by benmccann** [comment]
I've submitted another pull request to add a notification upon successful attach. Looks like that was the other one I missed
https://github.com/fsouza/go-dockerclient/pull/81

**Comment by benmccann** [comment]
Okay, I think that all the commits should be upstream now. One caveat is that the even stream didn't get added because they've added own version, so there will be some changes required here for that part of the migration https://github.com/fsouza/go-dockerclient/commit/15cbbdba1d0a320de42d917ed0edc4c8b865e6b1

**Comment by titanous** [comment]
Thanks! We have a release imminent, so I'm not going to make these changes yet, but I'll take a look.

**Comment by titanous** [comment]
@fsouza btw, I thought you were going to go with our event stream implementation? The one you merged looks overly complicated.

**Comment by progrium** [comment]
@fsouza also is a bit buggy: https://github.com/fsouza/go-dockerclient/issues/101

**Comment by titanous** [comment]
@benmccann I'm not really interested in using the upstream events implementation given the complexity and apparent bugs.

**Comment by progrium** [comment]
Turns out the bug is likely in Docker. I would prefer a simpler implementation though.

**Comment by benmccann** [comment]
I can't really comment on one implementation vs. the other. Perhaps @fsouza has thoughts there. I'd love to get the two converged somehow

**Comment by benmccann** [comment]
It's a shame Flynn still uses its own fork of go-dockerclient :-(
