### ISSUE TITLE
allow suggesting internal ports

### ISSUE THREAD

**Issue by progrium** [flynn-archive/flynn-host#5]
lorne should manage all public ports, but there will be cases where a container will not using PORT or be easily configurable to use a specific port. if a container exposes known port it should be possible to schedule a job that connects them up. perhaps instead of exposing the optional internal port with number of ports to open, lorne automatically exposes any "exposed" ports from the container definition?

**Comment by titanous** [comment]
Hmm, in that case how is the process informed of the external port? Can you give some concrete use cases for this?

**Comment by progrium** [comment]
It already knows. This is for cases when people want to use existing
container images since if you're doing your own you can tool them however,
but if you're using something existing you don't want to have to much
around with how they work. Here is an example:

https://index.docker.io/u/crashsystems/gitlab-docker/

On Thu, Jan 9, 2014 at 9:25 AM, Jonathan Rudenberg <notifications@github.com

> wrote:
> 
> Hmm, in that case how is the process informed of the external port? Can
> you give some concrete use cases for this?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/lorne/issues/5#issuecomment-31941998
> .

## 

Jeff Lindsay
http://progrium.com

**Comment by titanous** [comment]
Without service discovery usage in the container, how are you going to figure out how to access it?

**Comment by progrium** [comment]
Maybe my scheduler will register it.

On Thu, Jan 9, 2014 at 7:48 PM, Jonathan Rudenberg <notifications@github.com

> wrote:
> 
> Hmm, without service discovery usage in the container, how are you going
> to figure out how to access it?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/flynn/lorne/issues/5#issuecomment-31996297
> .

## 

Jeff Lindsay
http://progrium.com
