### ISSUE TITLE
Auth support

### ISSUE THREAD

**Issue by benmccann** [flynn-archive/flynn-host#6]
I know auth isn't planned until a bit later, but I'd argue it might be higher priority that some other features because it's so hard to create your own workaround. All the other features are nice, but not critical. I could schedule tasks myself, use nginx instead of a service-aware router, build packages myself, etc. but it's really hard to do auth myself.

**Comment by titanous** [comment]
That's not what's been indicated to us by any of our current users/prospective sponsors. Most companies run their production systems on networks that are trusted. We will absolutely get to it though.

**Comment by benmccann** [comment]
Sure, even on a private network though it's still nice to have auth so that you can log who is doing what. Also, if someone does compromise one machine you don't want them having control over absolutely all of your infrastructure. That being said, I realize you have a lot on your plate right now and I'm excited for the MVP release.

**Comment by titanous** [comment]
I'm going to close this as it's not specific to flynn-host. We absolutely will end up with robust auth{z,n}.
