### ISSUE TITLE
service API review, suggestions

### ISSUE THREAD

**Issue by progrium** [flynn-archive/flynn-host#7]
Current API:

```
JobList
GetJob
StopJob
Stream
```

Only suggestions are to make JobList and Stream more consistent / explicit.

Suggested API:

```
ListJobs
GetJob
StopJob
StreamEvents
```

I can see JobList as a noun abbreviating the Get/List, but since List is often an expected verb, seeing it as part of the noun is confusing. ListJobs seems to clear that up pretty easily. Especially since that abbreviation is not followed with the other methods.

Stream is also either being ambiguous or breaking convention. If it could be StreamJobs, it's being inconsistent. If it's StreamEvents, it needs to be clear about it, and I think StreamEvents is more accurate than StreamJobs.

**Comment by titanous** [comment]
:+1:
